version: '3.8'
services:
  redis:
    image: redis:8.4.0
    ports:
      - '6379:6379'
    command: ['redis-server', '--save', '', '--appendonly', 'no']

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-notifly}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql

  mongo:
    image: mongo:8.2.2
    command: ['mongod', '--bind_ip_all']
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
